### ISSUE TITLE
Add CORSMiddleware to permit frontend to access auth flow etc.

### ISSUE THREAD

**Issue by danielsilverstone-ct** [flathub/backend#108]
The new frontend has a server-side rendering portion as well as user-agent driven code.

The former can easily access the backend's APIs, but the latter is bound by the rules of CORS.  As the backend is, at least in development mode, on a different origin (different port) this means it has to permit the operation in order that browsers will permit JS running in them to access the backend.

This should be as simple as adding an appropriately configured CORSMiddleware, however we should give some consideration to how we might deal with this for production.  e.g. perhaps serving the entire `backend` under `/api` on the new site if we want to avoid a need for CORSMiddleware; or else if we're up for anyone using our APIs themselves, we could simply permit `*`, though that's a tad more difficult to then persuade browsers of.  I think we should err toward CORSMiddleware of some persuasion, so for now it'll be right to put this together in `backend`.

**Comment by razzeee** [comment]
Should this b closed?

**Comment by danielsilverstone-ct** [comment]
@razzeee Yep, well spotted, thanks.
