### ISSUE TITLE
Add /arches endpoint

### ISSUE THREAD

**Issue by swschilke** [flathub/backend#16]
Hallo, 

similar to Snapcraft (.io) it would be good to see and be able to filter depending on the supported architecture/OS (like ARM/Raspberry Pi OS).

Regards

.

**Comment by barthalion** [comment]
The easiest way would be to parse the output of `flatpak remote-ls --system --arch='*' --app flathub --columns=ref`. Refs are in form of `app/$ID/$arch/$branch`.

**Comment by swschilke** [comment]
I think my title describes the issue better.

What about thinking about the user and his experience. This is user unfriendly as it's can get. The platform/visualisation should provide you with that information without have to run cryptic command lines. Snap is better in that respect, at least they show you in their directory which platforms, distributions or systems are supported.

**Comment by barthalion** [comment]
This is repository for the backend. There's nothing to do for frontend if we don't expose this information here first. I'm not sure what did you expect by opening an issue for the server component.

**Comment by hfiguiere** [comment]
Frontend issue is https://github.com/flathub/linux-store-frontend/issues/263

**Comment by swschilke** [comment]
> This is repository for the backend. There's nothing to do for frontend if we don't expose this information here first. I'm not sure what did you expect by opening an issue for the server component.

I did an issue at the frontend and somebody there mentioned I should do it here, in the backend part.

**Comment by barthalion** [comment]
Fixed via https://github.com/flathub/backend/pull/39.
