### ISSUE TITLE
Update /picks via GitHub via HTTP

### ISSUE THREAD

**Issue by barthalion** [flathub/backend#18]
Currently backend ships "hardcoded" picks data. It should be possible to update it dynamically without rebuilding entire image, so @bertob can updated it without our help.

**Comment by tchx84** [comment]
Just to expand on this, it would require:

1. **Persistence**. The simplest approach would be (a) JSON files (as this is not an common operation) or (b) we integrate a proper db service.
2. **Auth**. The simplest approach would be (a) "hardcoded" X-API-Key, check this [approach](https://github.com/tchx84/linka/blob/master/app/authentication.py#L48) I use in another project or (b) we introduce users and groups concept.
3. **UI**. The simplest would be the fastapi auto-generated `/docs`, or we design the "admin" experience which would require (2.b).

**Comment by barthalion** [comment]
Fixed via https://github.com/flathub/backend/pull/37.

**Comment by bertob** [comment]
So is there a new process I should use for updating editor's choice apps? Are there docs for how to do it the new way?

**Comment by barthalion** [comment]
Not at the moment, but I'll let you know when website starts using the new API.
