### ISSUE TITLE
Add /popular endpoint

### ISSUE THREAD

**Issue by barthalion** [flathub/backend#19]
The popular section in Angular frontend is crafted manually, based on the number of page views from Google Analytics/Matomo.

After @nedrichards:

>  1. Make popular apps  driven by actual app updates and installs and make the list update automatically and regularly. Limit the category to the top 20 or 30 results (approx 2% of the total app base) which should ensure that these items are actually popular.
>    - Consideration – examine a listing that does/does not include deltas
>    - Ensure that we can calculate a ‘per arch’ version of this list, for when we have a filtered version of the website (given light traffic in some architectures we should experiment with both a combined list that is filtered by architecture availability as well as a listing that is just built from per architecture popularity)
>  2. Have a method to randomise the returned apps within the category to make sure that the front page appears to be visually different on most page loads, whilst also containing recognisable apps.

**Comment by tchx84** [comment]
@barthalion where can I learn more about how these json stats get generated?
