### ISSUE TITLE
Regression: deleting EOL'ed apps

### ISSUE THREAD

**Issue by barthalion** [flathub/backend#21]
As shown by https://github.com/flathub/flathub/issues/1976, apps which have been marked EOL are not correctly removed from the database.

**Comment by bilelmoussaoui** [comment]
I think we should have a is_eoled attribute in the database and just not show them; this way we can redirect api requests to X that was eoled to redirect to Y

**Comment by barthalion** [comment]
@bilelmoussaoui Mind opening a separate issue for that? It would require some summary poking, while I just want to ensure we don't have any regressions as compared to Java backend here.
