### ISSUE TITLE
Some apps have missing icons, probably due to icon type="remote"

### ISSUE THREAD

**Issue by jgarciao** [flathub/backend#24]
If you go to https://flathub.org/apps/category/All you'll see some apps with missing icons.

For example:
https://flathub.org/apps/details/com.anydesk.Anydesk
https://flathub.org/apps/details/com.github.taiko2k.avvie
https://flathub.org/apps/details/org.bluej.BlueJ
https://flathub.org/apps/details/org.claws_mail.Claws-Mail
https://flathub.org/apps/details/com.sigmyne.crush
https://flathub.org/apps/details/com.discordapp.Discord
https://flathub.org/apps/details/org.small_tech.Gnomit
https://flathub.org/apps/details/com.github.utsushi.Utsushi
https://flathub.org/apps/details/com.sublimetext.three

I think the problem is that some of this apps (or all) have in the appstream a mix of icon type remote and cached.

For example, sublime text:
```
    <icon type="remote">https://raw.githubusercontent.com/flathub/com.sublimetext.three/master/com.sublimetext.three-128.png</icon>
    <icon type="remote">https://raw.githubusercontent.com/flathub/com.sublimetext.three/master/com.sublimetext.three-64.png</icon>
    <icon type="cached" height="128" width="128">com.sublimetext.three.png</icon>
    <icon type="cached" height="64" width="64">com.sublimetext.three.png</icon>
```

https://flathub.org/apps/details/com.sublimetext.three

This is what the backend api returns: https://flathub.org/api/v1/apps/com.sublimetext.three
```
"iconDesktopUrl":"https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/https://raw.githubusercontent.com/flathub/com.sublimetext.three/master/com.sublimetext.three-128.png",
"iconMobileUrl":"https://dl.flathub.org/repo/appstream/x86_64/icons/128x128/https://raw.githubusercontent.com/flathub/com.sublimetext.three/master/com.sublimetext.three-128.png"
```

Its possible that the backend is hardcoding https://dl.flathub.org/repo/appstream/x86_64/icons/128x128 for all icons?

**Comment by barthalion** [comment]
This was fixed with https://github.com/flathub/backend/pull/23.

**Comment by jgarciao** [comment]
Thanks!

El dc., 30 de des. 2020, 10:58, Bartłomiej Piotrowski <
notifications@github.com> va escriure:
