### ISSUE TITLE
iconDesktopUrl shoud use 128x128 icons if available

### ISSUE THREAD

**Issue by jgarciao** [flathub/backend#31]
As reported in[ this issue](https://github.com/flathub/linux-store-frontend/issues/272) some apps like jamovi show low resolution icons. I think this is because the new backend is using 64x64 icons in the field iconDesktopUrl 

Values in the old backend: http://45.55.104.129/api/v1/apps/org.jamovi.jamovi
```
"iconDesktopUrl":"/repo/appstream/x86_64/icons/128x128/org.jamovi.jamovi.png",
"iconMobileUrl":"/repo/appstream/x86_64/icons/64x64/org.jamovi.jamovi.png"
```

Values in the new  backend:  http://flathub.org/api/v1/apps/org.jamovi.jamovi
```
"iconDesktopUrl":"https://dl.flathub.org/repo/appstream/x86_64/icons/64x64/org.jamovi.jamovi.png",
"iconMobileUrl":"https://dl.flathub.org/repo/appstream/x86_64/icons/64x64/org.jamovi.jamovi.png"
```

The old backend was checking in the appstream if there was a 128x128 icon available to use in iconDesktopUrl and, in case it was not available, it used the 64x64 icon.

https://github.com/flathub/linux-store-backend/blob/da80c7bc96c9d7f6cb30723d7e1cf2e413a0a766/src/main/java/org/flathub/api/service/UpdateServiceImpl.java#L628

**Comment by AsciiWolf** [comment]
Not sure what changed, but it looks like that the issue does not happen anymore.

**Comment by AsciiWolf** [comment]
Anyway, it looks like that apps using remote icons in their AppData are still affected by this issue. For example [Viber](https://flathub.org/apps/details/com.viber.Viber) that has both 64x64 and [128x128](https://github.com/flathub/com.viber.Viber/blob/master/com.viber.Viber.appdata.xml#L43) icons in their AppData, but only the 64x64 one seems to be displayed on Flathub.

**Comment by barthalion** [comment]
This should be fixed via https://github.com/flathub/backend/pull/32

That being said, maintainers who decide to use remote icons should make sure to include only one with sufficient quality as appstream-glib strips height/width metadata.

**Comment by AsciiWolf** [comment]
Parsec uses a non-remote 512x512 png icon and still [seems to have](https://flathub.org/apps/details/com.parsecgaming.parsec) the same issue.
