### ISSUE TITLE
Please check for / filter out apps with @@ in the Exec field

### ISSUE THREAD

**Issue by smcv** [flathub/backend#46]
flatpak/flatpak#4146 describes a sandbox escape that could be carried out by a malicious Flatpak app, and is not yet fixed in Flatpak. It occurs to me that Flathub would be well-placed to mitigate that vulnerability by refusing to publish apps that export a `.desktop` file where the `Exec` field contains a token starting with `@@`.

**Comment by razzeee** [comment]
This has been fixed in the meantime, so not sure if it should be pursued
