### ISSUE TITLE
Too many search results

### ISSUE THREAD

**Issue by i-need-to-tell-you-something** [flathub/backend#53]
I don't know what exactly is going wrong but I noticed a pattern which may point to some bug with the search.

## Expected 
When searching for[ `minutor`](https://flathub.org/apps/search/minutor) or [`lutris`](https://flathub.org/apps/search/lutris) I get 0-10 results roughly. Probably 0 since those package don't seem flatpakked yet.

## Actual
When searching for[ `minutor`](https://flathub.org/apps/search/minutor) or [`lutris`](https://flathub.org/apps/search/lutris) I get 1212 search results. Recently it changed to 1213 search results. Both strings are unlikely to be in the descriptions of all of those packages and those package pages I tried did not yield a result to CTRL+F and "minutor" or "lutris".

**Comment by librebob** [comment]
Searching `teeworl` yields the same result. Agree this should be addressed as it may turn away new users when the website seemingly fails as it tries to load over 1000 results.

**Comment by i-need-to-tell-you-something** [comment]
For me, it loads the 1000+ results perfectly - just that I was instead expecting to either get a clear "no such package" or a list of matches. It is confusing and looks broken.

**Comment by razzeee** [comment]
I have no idea, when it might be migrated or when/if somebody is still maintaining the old backend. Sorry.

**Comment by razzeee** [comment]
I've checked the new site with the search you supplied and it correctly returns zero results.
