### ISSUE TITLE
Missing API endpoints

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/backend#7]
While working on the frontend part, I've noticed the following API endpoints 

- [ ] Popular
- [x] Editor's Pick Apps
- [x] Editor's Pick games

**Comment by bilelmoussaoui** [comment]
For the editor's pick apps, it could be just a static json for now until we figure out how to handle that correctly

**Comment by tchx84** [comment]
> For the editor's pick apps, it could be just a static json for now until we figure out how to handle that correctly

makes sense, if @barthalion has not started yet I can get the "picks" ones done quick.

**Comment by razzeee** [comment]
Can we close this?

**Comment by barthalion** [comment]
Yup!
