### ISSUE TITLE
Categories: merge Game & Games

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/backend#8]
Seems some games & are using Game (which is the correct category) and others are using Games. Would be nice to automatically return both Game/Games in for /category/Game.

Which makes me wonder if we should return a 404 if the category isn't part of the desktop spec.

**Comment by tchx84** [comment]
> Seems some games & are using Game (which is the correct category) and others are using Games. Would be nice to automatically return both Game/Games in for /category/Game.
> 
> Which makes me wonder if we should return a 404 if the category isn't part of the desktop spec.

Weird, aren't category names validated by `appstream-util validate` ?
