### ISSUE TITLE
Write placeholder API implementation to permit frontend development to proceed

### ISSUE THREAD

**Issue by JamesPrice76** [flathub/backend#95]

**Comment by danielsilverstone-ct** [comment]
Once we've settled an initial API design in #94 we should add to the backend a placeholder API which can be enabled in development and disabled in production. This will then allow the frontend to begin implementation against that API without needing to wait for the whole database and github auth to be sorted out.

**Comment by danielsilverstone-ct** [comment]
While I've put this into 'in progress' I'm not sure if we should merge it, so we should have a chat at standup on Monday.
