### ISSUE TITLE
Implement Github authentication flow

### ISSUE THREAD

**Issue by JamesPrice76** [flathub/backend#98]

**Comment by danielsilverstone-ct** [comment]
This is the meat of the user creation and login flow.  Github authentication is the first model we're going to support, though it will not be the last.  In addition we will need to create a 'Flathub backend test' OAuth app on Github and ensure that the development environment has that client ID etc.  Alternatively we could include instructions to permit any developer to set up a github oauth app of their own for testing; protecting the official Flathub Auth Client ID and secret when we do #100
