### ISSUE TITLE
Implement user deletion flow

### ISSUE THREAD

**Issue by JamesPrice76** [flathub/backend#99]

**Comment by danielsilverstone-ct** [comment]
If users can be created, they ought to be able to be deleted.  We should implement a suitable "Please delete my user" flow.  Since we're not storing any particularly critical data in the database which doesn't exist in other places, this ought to be a fairly low risk thing to permit.

**Comment by razzeee** [comment]
Still, this should mean, that a previously `verified` app should change to `unverified` I think. At least that's what I would think, @barthalion will know.

Anyway, might not be part of the initial implementation for user deletion.

**Comment by ajr0d** [comment]
I've put together a gist for this as a proposal: https://gist.github.com/ajr0d/ffce4425486ad66a2c6b69395fb012ce
